### ISSUE TITLE
Album for the library

### ISSUE THREAD

**Issue by heyjarrod** [rknightuk/perfect-albums#2]
Not sure if this is the right way to request a submission to the site, but this is my perfect album:

[`~`How I’m Feeling`~` by Lauv (2020)](https://album.link/i/1480846311)

And [my blog post](https://heydingus.net/blog/2024/8/the-perfect-album) about it.

Thanks Robb; you’re the best!

**Comment by rknightuk** [comment]
Hey Jarrod - if you have a little look you'll see it there already, I did it last week but totally forgot to message you 😅
